name: metamorphic-mixtape
region: nyc
services:
  - name: http-adapter
    image:
      registry: ghcr.io
      repository: ghcr.io/OWNER/metamorphic-mixtape
      tag: latest
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    run_command: node dist/http/index.js
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
